name: "e-commerce-dashboard"
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.4.1
  - dash=2.18.2
  - dash-bootstrap-components=1.7.1
  - python=3.11.11
  - pandas=2.2.3
  - geopandas=1.0.1
  - pip
  - pip:
      - dash-vega-components==0.11.0
      - gitpython==3.1.43
      - vegafusion==1.6.9
      - vegafusion-python-embed==1.6.9
      - vl-convert-python==1.7.0
      - flask-caching==2.1.0