name: "e-commerce-dashboard"
channels:
  - conda-forge
  - defaults
dependencies:
  - altair-all=5.5.0
  - dash=2.18.2
  - dash-bootstrap-components=1.7.1
  - python=3.13.0
  - pandas=2.2.3
  - geopandas=1.0.1
  - pip
  - pip:
      - dash-vega-components